### ISSUE TITLE
Untested Mock SNS

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/docs#13]
is untested the right word? is this insecure / not production ready? Untested sounds like we've never tried it...

_Originally posted by @kristinaspring in https://github.com/xmidt-org/docs/pull/11/files_

**Comment by kristinaspring** [comment]
https://github.com/xmidt-org/docs/pull/11/files#r318185637

**Comment by joe94** [comment]
@kristinaspring, it should suffice to say: "For local development/testing..."

I don't see the need to include the Note

**Comment by kristinaspring** [comment]
I agree.

To do:
- [ ] Remove this line: https://github.com/xmidt-org/docs/blame/master/content/docs/operating/caduceus.md#L33
