### ISSUE TITLE
Service Name Capitalization

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/docs#15]
What is our stance on service names? Should they be capitalized? I didn't include comments on this because I'm not sure (and I'm fairly sure I didn't capitalize them in readmes I have modified).

**Comment by joe94** [comment]
@kristinaspring Do you mean service names in general or just in headings/titles. I would say capitalized in headings and all lowercase in text.

**Comment by kristinaspring** [comment]
I think they should be capitalized everywhere, other than code/configuration where things are case sensitive and lowercase is expected.  Since I consider our service names to be proper names, grammatically they should be capitalized.

**Comment by joe94** [comment]
@kristinaspring SGTM

**Comment by kristinaspring** [comment]
to do:
- [ ] go through the markdown files in `/content/docs/` and modify any service/project names to be capitalized

name examples:
XMiDT, Webpa, Codex, Talaria, Caduceus, Scytale, Petasos, Themis, Tr1d1um, Svalinn, Gungnir, Heimdall, Fenrir

**Comment by harrythehat1975** [comment]
I think this is right up my alley. I'm going to work on this
